Updated Gradle plugin to 1.16.0 due to the exception NoClassDefFoundError: org/gradle/api/publish/ivy/internal/publication/DefaultIvyPublicationIdentity in Gradle 8.4, https://github.com/JetBrains/gradle-intellij-plugin/issues/1469
See release notes for gradle plugin 1.16.0:
https://github.com/JetBrains/gradle-intellij-plugin/releases/tag/v1.16.0